### ISSUE TITLE
How do i connect to redis from outside kubernetes

### ISSUE THREAD

**Issue by avipan** [amaizfinance/redis-operator#11]
I see service is being created with port 6379. but i don't see any container ports defined in statefulset template once created. 

when i use redis-cli externally to connect it says Could not connect to Redis No route to host

**Comment by nrvnrvn** [comment]
Hi @avipan!

container ports can be defined purely for information purposes.
Here is the quote from the official kubernetes [documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#container-v1-core):

> Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network.

Other applications are expected to connect to Redis through the appropriate Service.

If you need to connect to Redis outside of the Kubernetes cluster you should also consult the official kubernetes [documentation on this topic](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#accessing-services-running-on-the-cluster).

If you still have problems connecting to Redis please provide a more detailed description of the issue you've faced so that I could address it more specifically.

**Comment by avipan** [comment]
Hi @nrvnrvn 

I was able to connect to redis from outside of kubernetes after creating nodePort service. Thanks for the doc.
its good to have nodePort service as part of operator along with clusterIp & headless services.

**Comment by nrvnrvn** [comment]
Great to know you were able to connect!

There is a number of resources that are generated by the operator, three services among them.
Headless service is required for the StatefulSet. ClusterIP services for all instances and for the master instance are provided for convenience. ClusterIP services is a common means for connecting application inside of the Kubernetes cluster.

Nodeport service is a special case for exposing a service to the outside of a cluster.

I would rather not generate it inside the operator since as you can see it is rather cheap and easy to do it by yourself.

For instance, here at Amaiz we are not relying on the operator generated ClusterIP services because we had been using a service with a different name before switching to the Redis operator and we just created a simple clusterIP service matching our needs and put it along with the Redis resource in git.
