### ISSUE TITLE
"go mod tidy" fails in current version

### ISSUE THREAD

**Issue by aignatov** [amaizfinance/redis-operator#21]
The following issue happens when you run command below. As result this project can't be built
➜  git:(master) go mod tidy -v
go: github.com/operator-framework/operator-sdk@v0.10.0 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190128024246-5eb7ae5bdb7a requires
	github.com/operator-framework/operator-registry@v1.0.4 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190105193533-81104ffdc4fb requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found

Looks like it requires bumping of operator-sdk

**Comment by nrvnrvn** [comment]
👻 The ghost of [left-pad](https://www.theregister.com/2016/03/23/npm_left_pad_chaos/) is around the corner!

The funniest thing is that there is even no `goautoneg` inside the vendor folder hence it is not needed.

See https://github.com/golang/go/issues/41562

As for bumping operator-sdk it turns out that operator-sdk and kubebuilder shared a lot in the past and now operator-sdk basically encapsulates the kubebuilder but their full integration is still [WIP](https://github.com/kubernetes-sigs/kubebuilder/projects/7). [This](https://github.com/operator-framework/operator-sdk/blob/8208609772a779147a2c6c4b555ae003c36a1b6f/proposals/kubebuilder-integration.md) is also a good read.

I've given a try to kubebuilder and it seems to work fine. I will try to stabilize this migration a bit and push to a separate branch if you are curious.

**Comment by aignatov** [comment]
We may go with bump to one of operator-sdk version which doesn't import missed module. I mean version like v0.17.x works perfectly. I was successfully updated redis-operator in downstream with minimal code changes to this version and can provide a patch if you'd like ;-).
