### ISSUE TITLE
PersistentVolume mounted to /data with root group, not following securityContext.fsGroup

### ISSUE THREAD

**Issue by kubacerny** [amaizfinance/redis-operator#33]
Seems like securityContext.fsGroup is not applied to the volume.

When I uncomment persistentVolumeClaimTemplate in https://github.com/amaizfinance/redis-operator/blob/master/example/k8s_v1alpha1_redis_cr.yaml, it correctly mounts the volume to redis /data directory. But it has only root owner and group and redis cannot write to this directory. Seems like securityContext.fsGroup is not applied to the volume. Like it is not passed to StatefulSet securityContext.fsGroup.

```
redis:
     securityContext:
           fsGroup: 7777777
```

**Comment by itek09** [comment]
Hi there!

I have the same problem, this is my generated securityContext:

` ``      securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 7777777
          runAsNonRoot: true
          runAsUser: 7777777```

**Comment by nrvnrvn** [comment]
There are two types of Security Contexts:
* https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podsecuritycontext-v1-core
* https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core

Turns out the example is misleading in this regard as it only mentions the container security context and passes fsGroup there whereas fsGroup belongs to the Pod Security Context:
* https://github.com/amaizfinance/redis-operator/blob/master/example/k8s_v1alpha1_redis_cr.yaml#L97
* https://github.com/amaizfinance/redis-operator/blob/master/deploy/crds/k8s_v1alpha1_redis_crd.yaml#L137

**Comment by nrvnrvn** [comment]
fixed the example.
@itek09 @kubacerny please refer to [this commit](https://github.com/amaizfinance/redis-operator/commit/f32c1cff791890873a99ba9dda8daba26b634697#diff-7f0d1387e953c7a2b354def5e7a1ca6df12e135c9bc064f5a220ab81b51a32d2R64), change the security Context on your side and let me know if it works.

**Comment by nrvnrvn** [comment]
I have checked it from my side. fsGroup is applied correctly once set up in the PodSecurityContext.

Let me know if you still experience the issue. I will re-open this ticket and we'll delve into it.
